Injector:
  RODB:
    class: MySQLDatabase
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLDatabase:
    class: AopProxyService
    properties:
      proxied: %$RODB
      beforeCall:
        query:
          - %$ReadOnlyAspect
        preparedQuery:
          - %$ReadOnlyAspect

ReadOnlyMode:
  activate: 1
  throw-exceptions: 1