Injector:
  RODB:
    class: MySQLDatabase
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLDatabase:
    class: AopProxyService
    properties:
      proxied: %$RODB
      beforeCall:
        query:
          - %$ReadOnlyAspect
        preparedQuery:
          - %$ReadOnlyAspect
  ReadOnlyAspect:
    properties:
      activate: 1
      throwExceptions: 0